Added css classes depending on popover state
openvinotoolkit/cvat pull request #2624
Opened 2020-12-28 14:11 UTC by bsekachev

### Motivation and context
To solve some issues during testing we need additional css classes, that appear after any popover animations. 

### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2020-12-28 19:00 UTC, dvkruchinin requested changes

2020-12-28 19:01 UTC, dvkruchinin commented
I also noticed a change in the popover view for tag 
![setup_tag_popover](https://user-images.githubusercontent.com/33020454/103237300-434cfa00-4958-11eb-9a81-c92353eb2e7f.jpg)

2020-12-29 06:46 UTC, bsekachev commented on tests/cypress/support/commands.js
> +        .parents(objectType === 'tag' ? '.cvat-setup-tag-popover-content' : '.cvat-draw-shape-popover-content')
Sure, I suppose we do not need using regex in this case.

2020-12-29 06:46 UTC, bsekachev commented
> I also noticed a change in the popover view for tag
> ![setup_tag_popover](https://user-images.githubusercontent.com/33020454/103237300-434cfa00-4958-11eb-9a81-c92353eb2e7f.jpg)

Fixed

2020-12-29 06:52 UTC, dvkruchinin commented on tests/cypress/support/commands.js
> +        .parents(objectType === 'tag' ? '.cvat-setup-tag-popover-content' : '.cvat-draw-shape-popover-content')
Thanks. Yes, now that there is a separation of popovers for the type of object being created, there is no need for using regex.

2020-12-29 07:35 UTC, merged