Add item Projects in User Guide
openvinotoolkit/cvat pull request #2632
Opened 2020-12-30 06:56 UTC by TOsmanov

### Motivation and context

This PR contains adding item Projects, fix mistakes and adding images. 
This PR fixed issue #2398

### How has this been tested?

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2020-12-30 13:51 UTC, ActiveChooN requested changes

2020-12-30 13:51 UTC, ActiveChooN commented on cvat/apps/documentation/user_guide.md
> +  1. Assigned to — is used to assign a project to a person. Start typing an assignee's name and/or choose the right person out of the dropdown list.
@TOsmanov, need to swap this two items to correspond to image.

2020-12-30 15:02 UTC, ActiveChooN approved these changes

2021-01-08 07:09 UTC, nmanovic approved these changes

2021-01-08 07:10 UTC, merged