[WIP] Added CI workflow to publish CVAT images
openvinotoolkit/cvat pull request #2766
Opened 2021-02-04 09:57 UTC by azhavoro

### Motivation and context
resolve #7 

### How has this been tested?
Manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
~~- [ ] I have added tests to cover my changes~~
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
~~- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2021-02-08 13:29 UTC, nmanovic commented on docker-compose.dev.yml
> +# Copyright (C) 2018-2021 Intel Corporation
```suggestion
# Copyright (C) 2021 Intel Corporation
```

2021-02-08 13:46 UTC, nmanovic commented on docker-compose.dev.yml
> +  cvat:
Why do we need the separate file?

2021-02-08 13:55 UTC, nmanovic commented on README.md
> +This software uses libraries from the [FFmpeg](https://www.ffmpeg.org) project.
Probably need to mention that we use only non-GPL code from ffmpeg. Also mention that exact steps to compile the project can be found in dockerfile...

2021-02-08 13:56 UTC, nmanovic commented on LICENSE
> +This software uses libraries from the [FFmpeg](https://www.ffmpeg.org) project.
Again, I prefer to mention that we use only non-GPL code from the software.

2021-02-08 14:08 UTC, nmanovic commented on Dockerfile
> +    make -j5 && make install && make clean && \
Please add a comment why clean instead of distclean

2021-02-08 14:09 UTC, nmanovic commented
@azhavoro , don't forget to add news into CHANGELOG.md

2021-02-08 14:16 UTC, nmanovic requested changes
Let's change comments for ffmpeg code and add info to CHANGELOG. Great job!

2021-02-08 14:17 UTC, nmanovic commented
@azhavoro , also need to fix codacy issues.

2021-02-09 17:00 UTC, nmanovic commented
@azhavoro , any updates?

2021-02-12 08:17 UTC, nmanovic approved these changes
Great job! I didn't test it, just reviewed the code. For me it looks fine.

2021-02-12 08:18 UTC, merged

2021-02-12 08:20 UTC, nmanovic commented
@azhavoro , could you please notify all stakeholders about the achievement (gitter, Intel teams)? Need to clear emphasize why it is important (speed of the build, easy to deploy, alternative channel to distribute CVAT, etc).

2021-02-12 15:44 UTC, azhavoro commented
> @azhavoro , could you please notify all stakeholders about the achievement (gitter, Intel teams)? Need to clear emphasize why it is important (speed of the build, easy to deploy, alternative channel to distribute CVAT, etc).

Sure