Update launch.json
openvinotoolkit/cvat pull request #3625
Opened 2021-08-30 14:26 UTC by dhivyasreedhar

Changed .vscode\launch.json for compatibility issues.

Copyright (C) 2020-2021 Intel Corporation

SPDX-License-Identifier: MIT

### Motivation and context
Fixed [[#3525]](https://github.com/openvinotoolkit/cvat/issues/3525)
Chrome debugger for vs-code is deprecated now, so we should move to the JavaScript Debugger

### How has this been tested?
All tests were passed while testing in JavaScript Workflow

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [ ] I have updated the license header for each file (see an example below)

2021-09-03 09:19 UTC, ActiveChooN commented
@dhivyasreedhar, hi, thank you for your contribution. There is should be some browser debugger task, not a pure node process one. So I guess the correct type of script is `pwa-chrome`.

2021-09-04 11:36 UTC, dhivyasreedhar commented
> @dhivyasreedhar, hi, thank you for your contribution. There is should be some browser debugger task, not a pure node process one. So I guess the correct type of script is `pwa-chrome`.

@ActiveChooN So the type in the launch.json should be changed to 'pwa-chrome' ?

2021-09-05 10:08 UTC, ActiveChooN commented
> 
> 
> > @dhivyasreedhar, hi, thank you for your contribution. There is should be some browser debugger task, not a pure node process one. So I guess the correct type of script is `pwa-chrome`.
> 
> @ActiveChooN So the type in the launch.json should be changed to 'pwa-chrome' ?

Yes, it should.

2021-09-05 14:08 UTC, dhivyasreedhar commented
> > > @dhivyasreedhar, hi, thank you for your contribution. There is should be some browser debugger task, not a pure node process one. So I guess the correct type of script is `pwa-chrome`.
> > 
> > 
> > @ActiveChooN So the type in the launch.json should be changed to 'pwa-chrome' ?
> 
> Yes, it should.

@ActiveChooN  I have made the necessary changes. Check it out.

2021-09-06 07:56 UTC, ActiveChooN commented on .vscode/launch.json
> +            "type": "pwa-chrome",
```suggestion
            "type": "node",
```

2021-09-06 07:57 UTC, ActiveChooN requested changes

2021-09-06 07:57 UTC, ActiveChooN commented on .vscode/launch.json
> +            "type": "node",
```suggestion
            "type": "pwa-chrome",
```

2021-09-06 09:09 UTC, dhivyasreedhar reviewed
Changes reviewed.

2021-09-06 13:12 UTC, nmanovic approved these changes

2021-09-06 19:54 UTC, nmanovic approved these changes

2021-09-06 19:54 UTC, merged