Bug 4010
openvinotoolkit/cvat pull request #4092
Opened 2021-12-29 08:05 UTC by g-kartik

### Motivation and context

fixes #4010 - https://github.com/openvinotoolkit/cvat/issues/4010

When email verification is turned off in the all-auth settings, the rest-register api does not return auth-token key. This pull request solves the issue by returning the key in this condition.
Changes:
- Modify get_response_data of RegisterViewEx in iam views to add a new response field 'key' 
- The value of key will depend on the email verification setting of all-auth. If email verification is 'none', its value will be request user's auth token key else it will be 'None'.

### How has this been tested?

Tests
- Created tests for 'rest_register' api located in cvat/iam/tests/test_rest_apis.py to verify its response, both in case of email verification being turned on and turned off.
- From the root directory ran `python manage,.py test cvat.apps.iam.tests` to run the tests

### Checklist

- [x ] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- ~~[ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- ~~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x ] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2021 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

2021-12-29 19:01 UTC, bsekachev commented
Hi, @g-kartik 

Thank your for the contribution!
Please expect delay in review because of New Year coming, and have a nice New Year celebration!

2021-12-30 10:44 UTC, g-kartik commented
> Hi, @g-kartik 
> 
> Thank your for the contribution!
> Please expect delay in review because of New Year coming, and have a nice New Year celebration! 
> 

Okay, Thank you!

2022-01-12 09:41 UTC, azhavoro requested changes

2022-01-12 09:41 UTC, azhavoro commented on CHANGELOG.md
> +- Fixed to return auth token key when registration without email verification (<https://github.com/openvinotoolkit/cvat/pull/4092>)
Please move this line to `Fixed` section.

2022-01-14 13:41 UTC, azhavoro approved these changes

2022-01-17 12:56 UTC, nmanovic approved these changes
LGTM, thanks for the contribution!

2022-01-17 12:56 UTC, merged